version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: insa          # mot de passe root 
      MYSQL_USER: yoonusafe_user        # user tel que dans config.json
      MYSQL_PASSWORD: insa              # mot de passe user
      MYSQL_DATABASE: yoonusafe_db      # base à créer
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  backend:
    build: .
    container_name: backend_flask
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mariadb
    volumes:
      - ./config.json:/app/config.json
    command: python app.py

volumes:
  mariadb_data:
